export const CREATE_POST = "POST/CREATE_POST";
export const LIKE_POST = "POST/LIKE_POST";
export const DISLIKE_POST = "POST/DISLIKE_POST";
export const SAVE_POST = "POST/SAVE_POST";

export const DELETE_POST = "POST/DELETE_POST";

export const ADD_COMMENT = "POST/ADD_COMMENT";
export const DELETE_COMMENT = "POST/DELETE_COMMENT";
export const CHANGE_COMMENT = "POST/CHANGE_COMMENT";
