export const ADD_MESSAGE = "DIRECT/ADD_MESSAGE";
export const DELETE_MESSAGE = "DIRECT/DELETE_MESSAGE";
export const CHANGE_MESSAGE = "DIRECT/CHANGE_MESSAGE";

export const SET_ACTIVE_CHAT = "DIRECT/SET_ACTIVE_CHAT";
